platform :ios, '7.0'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'JSONKit', '~> 1.5pre'
pod 'EGOCache', '~> 2.1'
pod 'SDWebImage', '~> 3.7.1'
pod 'FMDB', '~> 2.4'
pod 'IBActionSheet', '~> 0.0.1'
pod 'RegexKitLite', '~> 4.0'
pod 'MBProgressHUD', '~> 0.9'
pod 'MBProgressHUDExtensions', '~> 0.0.1'
pod 'PullToRefreshCoreText', '~> 0.2'
pod 'pop'
